name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint
        run: flake8 .
      - name: Run tests
        run: pytest -q

  build-and-push:
    needs: test-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-iris:${{ github.sha }} .
      - name: Login to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - name: Push image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlops-iris:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mlops-iris:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-iris:latest